[depreceated] Removed User.organizations_pk #197
openwisp/openwisp-users pull request #198
Opened 2020-11-15 08:16 UTC by codesankalp

Removed organizations_pk method from AbstractUser class
of openwisp_users.base.models.py.

Reason - User.organizations_pk is deprecated in favor of
         User.organizations_dict and will be removed in a
         future version

Fixes #197

2020-11-15 08:24 UTC, devkapilbansal requested changes
Thanks @codesankalp 
You should consider removing the tests associated with it. There are some tests in which organizations_pk is used. 
Here is the one:-
https://github.com/openwisp/openwisp-users/blob/2bc6a51f81bc3bea5a41d0909dfb80aec2aa49c2/openwisp_users/tests/test_models.py#L46-L59

2020-11-15 08:30 UTC, devkapilbansal commented
@codesankalp See travis builds are failed too, you should run tests locally first before pushing your code

2020-11-15 08:46 UTC, codesankalp commented
@devkapilbansal @nemesisdesign 
https://github.com/openwisp/openwisp-users/blob/2bc6a51f81bc3bea5a41d0909dfb80aec2aa49c2/openwisp_users/tests/test_models.py#L61

I think user creation with the name `organizations_pk` is odd. 
Why don't we change this something to `test_user`?

2020-11-16 11:53 UTC, Purhan reviewed
@codesankalp Thanks, :smile: just a small change. Typo in the commit message, it should be `deprecated` .

2020-11-16 12:09 UTC, codesankalp commented
Thanks, @Purhan for correcting my mistake :bow:

2020-11-16 18:17 UTC, devkapilbansal reviewed
> @devkapilbansal @nemesisdesign
> https://github.com/openwisp/openwisp-users/blob/2bc6a51f81bc3bea5a41d0909dfb80aec2aa49c2/openwisp_users/tests/test_models.py#L61
> 
> I think user creation with the name `organizations_pk` is odd.
> Why don't we change this something to `test_user`?

@codesankalp in my opinion we should change it. :thinking:

2020-11-16 18:34 UTC, codesankalp commented
@devkapilbansal making a new issue for that will be good. What's your view?

2020-11-17 04:23 UTC, nemesisdesign approved these changes
Thanks @codesankalp @devkapilbansal :+1:

2020-11-17 04:25 UTC, merged