[fix] Restrict who can set objects to Organization=None #235
openwisp/openwisp-users pull request #239
Opened 2021-04-20 13:38 UTC by ManishShah120

Restrict Non-Super users from
setting objects to organization=None

Closes #235

2021-04-20 14:31 UTC, Purhan reviewed
LGTM :+1: but would be good to add a test as well.

2021-04-20 16:26 UTC, nemesisdesign requested changes
You see? What we needed could be implemented in 1 line.
This is what we have to strive for, achieve what we need with simplicity.

@Purhan is right, but I also think there are a few other things missing, so please add:

- one test, you could send a request to an API endpoint which has this serializer, using content-type text/HTML, which should give you a response from the browsable API, and there you can test for the presence of the null option, please make sure the test fails without your change and passes with it
- but also a line of doc in https://github.com/openwisp/openwisp-users#multi-tenant-serializers-for-the-browsable-web-ui which explains that the serializers are designed to not allow non-superadmin users to create shared objects
- in case of superusers, it would be great to show the same label for the null option as we do in the admin, if you can do that easily please try

2021-04-21 21:42 UTC, ManishShah120 commented
Hi, @nemesisdesign , @atb00ker , @Purhan 
- All the present API endpoints present in the `testapp` didn't allowed any shared objects creation for any model, so could not write tests with the present endpoints. To test this I had to introduce one extra endpoint for the `Template` Model, which allowed shared object creation.
- Have updated the docs.

2021-04-22 03:44 UTC, nemesisdesign requested changes
Great work @ManishShah120, see my comments below for minor cleanups and we'll be ready to merge.

2021-04-22 03:44 UTC, nemesisdesign commented on tests/testapp/tests/test_filter_classes.py
> +        response = self.client.get(path, **auth)
this is a lot cleaner:
```python
response = self.client.get(url, {'format': 'api'}, HTTP_AUTHORIZATION=f'Bearer {token}')
```

I noticed only now the same pattern in the rest of the file, I will open an issue shortly to clean that up later for now just clean this one please.

2021-04-22 03:44 UTC, nemesisdesign commented on README.rst
> +serializers obstructs non super-users from creating shared objects.
Please move the new sentence on its own line and let's change it to:

"These serializers do not allow non-superusers to create shared objects".

2021-04-22 03:49 UTC, nemesisdesign commented on tests/testapp/tests/test_filter_classes.py
> +        response = self.client.get(path, **auth)
Created issue: https://github.com/openwisp/openwisp-users/issues/242

2021-04-22 23:33 UTC, nemesisdesign approved these changes
Thanks!

2021-04-22 23:34 UTC, merged