[fix] Add permission to view org to operator
openwisp/openwisp-users pull request #304
Opened 2022-01-24 11:03 UTC by Aryamanz29

Fixes #276

2022-01-25 18:29 UTC, nemesisdesign requested changes
@Aryamanz29 the tests are failing, please always run tests locally before opening PRs.

2022-01-31 08:28 UTC, codesankalp commented on openwisp_users/tests/test_api/test_api.py
> +            r.data['permissions'], ['40: organization | Can view organization']
@Aryamanz29 You can use 
```
permission = Permission.objects.filter(codename='view_organization')
self.assertEqual(
            r.data['permissions'], [f'{permission.id}: organization | {permission.name}']
)
```

2022-01-31 08:34 UTC, codesankalp commented on openwisp_users/tests/test_api/test_api.py
> +            r.data['permissions'], ['40: organization | Can view organization']
Or you can use `assertIn` also.

2022-02-15 15:19 UTC, nemesisdesign approved these changes
Thanks!

2022-02-15 15:22 UTC, merged