Refactored base-email-view
openwisp/openwisp-users pull request #358
Opened 2023-09-28 19:49 UTC by MihirKohli

Resolved https://github.com/openwisp/openwisp-users/issues/354

2023-09-29 07:50 UTC, nemesifier requested changes
@MihirKohli please check the details of the build / QA check failures.

2023-09-29 07:50 UTC, nemesifier commented on openwisp_users/api/views.py
> +                and not qs.filter(pk=self.request.user.id).exists()
this should not be changed

2023-09-29 07:50 UTC, nemesifier commented on openwisp_users/api/views.py
> -            # the dev server, and for schema generation
do not remove these comments please

2023-09-29 12:37 UTC, MihirKohli commented on openwisp_users/api/views.py
> -            # the dev server, and for schema generation
> do not remove these comments please

updated commits review it please

2023-09-30 08:38 UTC, MihirKohli commented
made changes do check it

2023-10-02 12:04 UTC, nemesifier requested changes
> made changes do check it

Please change the commit message to:

```
[refactor] Refactor BaseEmailView to use the FilterByParent mixin #354

Closes #354
```

2023-10-02 12:04 UTC, nemesifier commented on openwisp_users/api/views.py
> +class BaseEmailView(ProtectedAPIMixin, FilterByParent, GenericAPIView):
Yeah ok, we're inheriting from this `FilterByParent` now but there's some code here in BaseEmailView which is now redundant and has to be removed, which is not being done in this patch, so the goal of the issue is not being reached yet.

2024-02-19 12:19 UTC, closed without merging